[package]
name = "morphorm-ecs"
version = "0.1.0"
edition = "2018"
description = "A mini ECS used for testing the morphorm crate."
license = "MIT"

[dependencies]
morphorm = {version = "0.6.1", path = "../"}
femtovg = {version = "0.7.1", default-features = false}
rand = "0.8.5"
slotmap = "1.0.6"